// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8By9yz1U7naw5VLbnJkYlBm6iuoq8Xcs',
    appId: '1:564863880384:web:35f89da1aad26166803125',
    messagingSenderId: '564863880384',
    projectId: 'foodpanda-8adb3',
    authDomain: 'foodpanda-8adb3.firebaseapp.com',
    storageBucket: 'foodpanda-8adb3.appspot.com',
    measurementId: 'G-FXZ5MLPEHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBPMAIV8faqmeKSdgoYkK-MhsP8S8LNI',
    appId: '1:564863880384:android:453ca0ce0854a183803125',
    messagingSenderId: '564863880384',
    projectId: 'foodpanda-8adb3',
    storageBucket: 'foodpanda-8adb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKo5wtAURra4vx5EUmv08WwbgW4qI-DMg',
    appId: '1:564863880384:ios:257d948ab7bd7323803125',
    messagingSenderId: '564863880384',
    projectId: 'foodpanda-8adb3',
    storageBucket: 'foodpanda-8adb3.appspot.com',
    iosClientId: '564863880384-qkiqqvu54q00udmvjpatgnlp9mh9bpud.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKo5wtAURra4vx5EUmv08WwbgW4qI-DMg',
    appId: '1:564863880384:ios:257d948ab7bd7323803125',
    messagingSenderId: '564863880384',
    projectId: 'foodpanda-8adb3',
    storageBucket: 'foodpanda-8adb3.appspot.com',
    iosClientId: '564863880384-qkiqqvu54q00udmvjpatgnlp9mh9bpud.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpanda',
  );
}
